# -*- coding: utf-8 -*-
#     BIDS Manager collect, organise and manage data in BIDS format.
#     Copyright © 2018-2020 Aix-Marseille University, INSERM, INS
#
#     This file is part of BIDS Manager. It generates the Generic Uploader
#     interface.
#
#     BIDS Manager is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     any later version
#
#     BIDS Manager is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with BIDS Manager.  If not, see <https://www.gnu.org/licenses/>
#
#     Authors: Samuel Medina, 2018-2020

# Form implementation generated from reading ui file 'generic_uploaderUI.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from generic_uploader.groupbox_modalite import GroupboxModalite
from math import ceil

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtWidgets.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(994, 912)
        MainWindow.setAutoFillBackground(False)
        req = [item for item in MainWindow.requirements['Requirements'].keys() if item != "Subject"]
        window_box_nb_vert = ceil(len(req)/2) + 2 + 2# 2 du sujet, 2 de la validation
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_10 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.groupBox_identite = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_identite.setMinimumSize(QtCore.QSize(400, 200))
        self.groupBox_identite.setMaximumSize(QtCore.QSize(361, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        self.groupBox_identite.setFont(font)
        self.groupBox_identite.setObjectName(_fromUtf8("groupBox_identite"))
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_identite)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.labelName = QtWidgets.QLabel(self.groupBox_identite)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(10)
        self.labelName.setFont(font)
        self.labelName.setObjectName(_fromUtf8("labelName"))
        self.gridLayout_5.addWidget(self.labelName, 0, 0, 1, 2)
        self.TextName = QtWidgets.QPlainTextEdit(self.groupBox_identite)
        self.TextName.setEnabled(True)
        self.TextName.setMaximumSize(QtCore.QSize(391, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        self.TextName.setFont(font)
        self.TextName.setTabChangesFocus(True)
        self.TextName.setReadOnly(False)
        self.TextName.setObjectName(_fromUtf8("TextName"))
        self.gridLayout_5.addWidget(self.TextName, 0, 3, 1, 3)
        self.labelFirstname = QtWidgets.QLabel(self.groupBox_identite)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(10)
        self.labelFirstname.setFont(font)
        self.labelFirstname.setObjectName(_fromUtf8("labelFirstname"))
        self.gridLayout_5.addWidget(self.labelFirstname, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(68, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem, 1, 1, 1, 2)
        self.TextPrenom = QtWidgets.QPlainTextEdit(self.groupBox_identite)
        self.TextPrenom.setEnabled(True)
        self.TextPrenom.setMaximumSize(QtCore.QSize(391, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        self.TextPrenom.setFont(font)
        self.TextPrenom.setTabChangesFocus(True)
        self.TextPrenom.setObjectName(_fromUtf8("TextPrenom"))
        self.gridLayout_5.addWidget(self.TextPrenom, 1, 3, 1, 3)
        self.labelBirthdate = QtWidgets.QLabel(self.groupBox_identite)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(10)
        self.labelBirthdate.setFont(font)
        self.labelBirthdate.setObjectName(_fromUtf8("labelBirthdate"))
        self.gridLayout_5.addWidget(self.labelBirthdate, 2, 0, 1, 2)
        self.dateEdit = QtWidgets.QDateEdit(self.groupBox_identite)
        self.dateEdit.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        self.dateEdit.setFont(font)
        self.dateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(1752, 9, 14), QtCore.QTime(0, 0, 0)))
        self.dateEdit.setObjectName(_fromUtf8("dateEdit"))
        self.gridLayout_5.addWidget(self.dateEdit, 2, 2, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(128, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem1, 2, 4, 1, 2)
        self.anonymize_patient_checkBox = QtWidgets.QCheckBox(self.groupBox_identite)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.anonymize_patient_checkBox.setFont(font)
        self.anonymize_patient_checkBox.setChecked(True)
        self.anonymize_patient_checkBox.setObjectName(_fromUtf8("anonymize"))
        self.gridLayout_5.addWidget(self.anonymize_patient_checkBox, 3, 0, 1, 2)
        # ajout du champ pour alias si non anonymisé
        self.id_textinfo = QtWidgets.QLabel(self.groupBox_identite)
        self.id_textinfo.setVisible(False)
        self.id_textinfo.setMaximumSize(QtCore.QSize(300, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        # font.setBold(True)
        font.setPointSize(10)
        self.id_textinfo.setFont(font)
        self.id_textinfo.setObjectName(_fromUtf8("id_info"))
        self.id_textinfo.setText("alternative ID")
        self.gridLayout_5.addWidget(self.id_textinfo, 3, 2, 1, 2)
        self.id_textbox = QtWidgets.QPlainTextEdit(self.groupBox_identite)
        self.id_textbox.setVisible(False)
        self.id_textbox.setMaximumSize(QtCore.QSize(350, 35))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(10)
        self.id_textbox.setFont(font)
        self.id_textbox.setObjectName(_fromUtf8("id_textbox"))
        self.gridLayout_5.addWidget(self.id_textbox, 3, 4, 1, 2)
        self.labelSexe = QtWidgets.QLabel(self.groupBox_identite)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(10)
        self.labelSexe.setFont(font)
        self.labelSexe.setObjectName(_fromUtf8("labelSexe"))
        self.gridLayout_5.addWidget(self.labelSexe, 4, 0, 1, 1)
        self.radioButtonM = QtWidgets.QRadioButton(self.groupBox_identite)
        self.radioButtonM.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        self.radioButtonM.setFont(font)
        self.radioButtonM.setObjectName(_fromUtf8("radioButtonM"))
        self.gridLayout_5.addWidget(self.radioButtonM, 4, 2, 1, 1)
        self.radioButtonF = QtWidgets.QRadioButton(self.groupBox_identite)
        self.radioButtonF.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        self.radioButtonF.setFont(font)
        self.radioButtonF.setObjectName(_fromUtf8("radioButtonF"))
        self.gridLayout_5.addWidget(self.radioButtonF, 4, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(137, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem2, 4, 4, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox_identite, 0, 3, 2, 2)
        '''self.pushButtonResume = QtGui.QPushButton(self.centralwidget)
        self.pushButtonResume.setEnabled(False)
        self.pushButtonResume.setObjectName(_fromUtf8("pushButtonResume"))
        self.gridLayout_10.addWidget(self.pushButtonResume, 5, 0, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(448, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem19, 5, 1, 1, 2)'''
        self.logo_ins = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        self.logo_ins.setFont(font)
        self.logo_ins.setText(_fromUtf8(""))
        self.logo_ins.setPixmap(QtGui.QPixmap(_fromUtf8("config/logoINSreduit.png")))
        self.logo_ins.setObjectName(_fromUtf8("logo_ins"))
        self.gridLayout_10.addWidget(self.logo_ins, window_box_nb_vert-1, 0, 1, 3)
        #spacerItem20 = QtWidgets.QSpacerItem(378, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        #self.gridLayout_10.addItem(spacerItem20, 7, 0, 1, 2)
        self.groupBox_log = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        self.groupBox_log.setFont(font)
        self.groupBox_log.setTitle(_fromUtf8(""))
        self.groupBox_log.setObjectName(_fromUtf8("groupBox_log"))
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_log)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        spacerItem21 = QtWidgets.QSpacerItem(512, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem21, 0, 0, 1, 1)
        self.listWidget = QtWidgets.QListWidget(self.groupBox_log)
        self.listWidget.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.listWidget.setFont(font)
        self.listWidget.setViewMode(QtWidgets.QListView.ListMode)
        self.listWidget.setModelColumn(0)
        self.listWidget.setSelectionRectVisible(False)
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        self.gridLayout_7.addWidget(self.listWidget, 1, 0, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox_log, 0, 0, window_box_nb_vert-1, 3)  # -1 du logo
        self.groupBox_list = []
        self.import_button_list = []
        # ===================== sam part for creation from requirement folder =============================
        # implantation groupbox
        # if "IeegGlobalSidecars" in MainWindow.requirements.requirements['Requirements'].keys():
        #     self.groupBox_implantation = GroupboxImplantation(MainWindow)
        #     self.gridLayout_10.addWidget(self.groupBox_implantation, 2, 3, 1, 2)
        #     self.groupBox_implantation.raise_()
        #
        #     self.groupBox_implantation = QtGui.QGroupBox(self.centralwidget)
        #     self.groupBox_implantation.setEnabled(False)
        #     self.groupBox_implantation.setMinimumSize(QtCore.QSize(400, 0))
        #     self.groupBox_implantation.setMaximumSize(QtCore.QSize(361, 16777215))
        #     font = QtGui.QFont()
        #     font.setFamily(_fromUtf8("Segoe UI"))
        #     self.groupBox_implantation.setFont(font)
        #     self.groupBox_implantation.setObjectName(_fromUtf8("groupBox_implantation"))
        #     self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_implantation)
        #     self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        #     self.label_10 = QtGui.QLabel(self.groupBox_implantation)
        #     font = QtGui.QFont()
        #     font.setFamily(_fromUtf8("Segoe UI"))
        #     font.setPointSize(10)
        #     self.label_10.setFont(font)
        #     self.label_10.setObjectName(_fromUtf8("label_10"))
        #     self.gridLayout_4.addWidget(self.label_10, 0, 0, 1, 1)
        #     spacerItem3 = QtGui.QSpacerItem(20, 38, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        #     self.gridLayout_4.addItem(spacerItem3, 0, 2, 2, 1)
        #     self.listElectrodeTypes = QtGui.QListWidget(self.groupBox_implantation)
        #     self.listElectrodeTypes.setEnabled(False)
        #     self.listElectrodeTypes.setMaximumSize(QtCore.QSize(131, 81))
        #     font = QtGui.QFont()
        #     font.setFamily(_fromUtf8("Segoe UI"))
        #     self.listElectrodeTypes.setFont(font)
        #     self.listElectrodeTypes.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        #     self.listElectrodeTypes.setResizeMode(QtGui.QListView.Adjust)
        #     self.listElectrodeTypes.setViewMode(QtGui.QListView.ListMode)
        #     self.listElectrodeTypes.setWordWrap(False)
        #     self.listElectrodeTypes.setObjectName(_fromUtf8("listElectrodeTypes"))
        #     item = QtGui.QListWidgetItem()
        #     self.listElectrodeTypes.addItem(item)
        #     item = QtGui.QListWidgetItem()
        #     self.listElectrodeTypes.addItem(item)
        #     item = QtGui.QListWidgetItem()
        #     self.listElectrodeTypes.addItem(item)
        #     item = QtGui.QListWidgetItem()
        #     self.listElectrodeTypes.addItem(item)
        #     self.gridLayout_4.addWidget(self.listElectrodeTypes, 1, 0, 3, 1)
        #     spacerItem4 = QtGui.QSpacerItem(80, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        #     self.gridLayout_4.addItem(spacerItem4, 2, 1, 1, 1)
        #     self.comboBoxImplantation = QtGui.QComboBox(self.groupBox_implantation)
        #     self.comboBoxImplantation.setEnabled(False)
        #     sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        #     sizePolicy.setHorizontalStretch(0)
        #     sizePolicy.setVerticalStretch(0)
        #     sizePolicy.setHeightForWidth(self.comboBoxImplantation.sizePolicy().hasHeightForWidth())
        #     self.comboBoxImplantation.setSizePolicy(sizePolicy)
        #     self.comboBoxImplantation.setMinimumSize(QtCore.QSize(150, 0))
        #     font = QtGui.QFont()
        #     font.setFamily(_fromUtf8("Segoe UI"))
        #     self.comboBoxImplantation.setFont(font)
        #     self.comboBoxImplantation.setDuplicatesEnabled(False)
        #     self.comboBoxImplantation.setObjectName(_fromUtf8("comboBoxImplantation"))
        #     self.comboBoxImplantation.addItem(_fromUtf8(""))
        #     self.comboBoxImplantation.addItem(_fromUtf8(""))
        #     self.comboBoxImplantation.addItem(_fromUtf8(""))
        #     self.comboBoxImplantation.addItem(_fromUtf8(""))
        #     self.gridLayout_4.addWidget(self.comboBoxImplantation, 2, 2, 1, 1)
        #     spacerItem5 = QtGui.QSpacerItem(28, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        #     self.gridLayout_4.addItem(spacerItem5, 2, 3, 1, 1)
        #     spacerItem6 = QtGui.QSpacerItem(20, 47, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        #     self.gridLayout_4.addItem(spacerItem6, 3, 2, 1, 1)
        #     self.gridLayout_10.addWidget(self.groupBox_implantation, 2, 3, 1, 2)
        # modality groupbox
        for i in range(0, len(MainWindow.moda_needed)):
            # self.groupBox_list.append(QtGui.QGroupBox(self.centralwidget))
            # self.groupBox_list[i].setEnabled(False)
            # self.groupBox_list[i].setMinimumSize(QtCore.QSize(195, 0))
            # self.groupBox_list[i].setMaximumSize(QtCore.QSize(175, 16777215))
            # font = QtGui.QFont()
            # font.setFamily(_fromUtf8("Segoe UI"))
            # self.groupBox_list[i].setFont(font)
            # self.groupBox_list[i].setObjectName(_fromUtf8("groupBox_" + MainWindow.moda_needed[i]))
            # self.groupBox_list[i].setTitle(MainWindow.moda_needed[i])
            # self.gridLayout_9 = QtGui.QGridLayout(self.groupBox_list[i])
            # self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
            # spacerItem7 = QtGui.QSpacerItem(20, 37, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
            # self.gridLayout_9.addItem(spacerItem7, 0, 0, 1, 1)
            # self.import_button_list.append(QtGui.QPushButton(self.groupBox_list[i]))
            # self.import_button_list[i].setEnabled(False)
            # sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
            # sizePolicy.setHorizontalStretch(0)
            # sizePolicy.setVerticalStretch(0)
            # sizePolicy.setHeightForWidth(self.import_button_list[i].sizePolicy().hasHeightForWidth())
            # self.import_button_list[i].setSizePolicy(sizePolicy)
            # self.import_button_list[i].setMinimumSize(QtCore.QSize(160, 40))
            # font = QtGui.QFont()
            # font.setFamily(_fromUtf8("Segoe UI"))
            # font.setPointSize(8)
            # self.import_button_list[i].setFont(font)
            # self.import_button_list[i].setObjectName(_fromUtf8("import_" + MainWindow.moda_needed[i]))
            # self.import_button_list[i].setText("import_" + MainWindow.moda_needed[i])
            # self.gridLayout_9.addWidget(self.import_button_list[i], 1, 0, 1, 1)
            # spacerItem8 = QtGui.QSpacerItem(20, 34, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
            # self.gridLayout_9.addItem(spacerItem8, 2, 0, 1, 1)
            # spacerItem9 = QtGui.QSpacerItem(174, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
            # self.gridLayout_9.addItem(spacerItem9, 3, 0, 1, 1)
            self.groupBox_list.append(GroupboxModalite(MainWindow.moda_needed[i]))
            impair = i % 2
            vert_pos = 2+i/2
            horz_pos = 3+impair
            self.gridLayout_10.addWidget(self.groupBox_list[i], vert_pos, horz_pos, 1, 1)
            self.groupBox_list[i].raise_()
        self.groupBox_validation = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_validation.setMinimumSize(QtCore.QSize(400, 0))
        self.groupBox_validation.setMaximumSize(QtCore.QSize(3610, 1500))
        self.groupBox_validation.setObjectName(_fromUtf8("groupBox_validation"))
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_validation)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        spacerItem22 = QtWidgets.QSpacerItem(20, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem22, 0, 0, 1, 1)
        spacerItem23 = QtWidgets.QSpacerItem(20, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem23, 0, 1, 1, 1)
        spacerItem24 = QtWidgets.QSpacerItem(20, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem24, 0, 2, 1, 1)
        self.pushButtonValidation = QtWidgets.QPushButton(self.groupBox_validation)
        self.pushButtonValidation.setEnabled(False)
        self.pushButtonValidation.setMinimumSize(QtCore.QSize(0, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(12)
        self.pushButtonValidation.setFont(font)
        self.pushButtonValidation.setObjectName(_fromUtf8("pushButtonValidation"))
        self.gridLayout_2.addWidget(self.pushButtonValidation, 0, 0, 1, 1)
        spacerItem25 = QtWidgets.QSpacerItem(48, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem25, 0, 1, 1, 1)
        self.pushButtonReset = QtWidgets.QPushButton(self.groupBox_validation)
        self.pushButtonReset.setEnabled(False)
        self.pushButtonReset.setMinimumSize(QtCore.QSize(0, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(12)
        self.pushButtonReset.setFont(font)
        self.pushButtonReset.setObjectName(_fromUtf8("pushButtonReset"))
        self.gridLayout_2.addWidget(self.pushButtonReset, 0, 1, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.groupBox_validation)
        self.progressBar.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        self.progressBar.setFont(font)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.gridLayout_2.addWidget(self.progressBar, 1, 0, 1, 1)
        spacerItem26 = QtWidgets.QSpacerItem(48, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem26, 1, 1, 1, 1)
        spacerItem27 = QtWidgets.QSpacerItem(68, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem27, 1, 1, 1, 1)
        self.labelProgressbar = QtWidgets.QLabel(self.groupBox_validation)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(10)
        self.labelProgressbar.setFont(font)
        self.labelProgressbar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelProgressbar.setText(_fromUtf8(""))
        self.labelProgressbar.setTextFormat(QtCore.Qt.AutoText)
        self.labelProgressbar.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.labelProgressbar.setObjectName(_fromUtf8("labelProgressbar"))
        self.gridLayout_2.addWidget(self.labelProgressbar, 3, 0, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox_validation, vert_pos + 1 , 3, 2, 2)
        #Add by Aude: Button Finish and Import
        self.pushButtonFinish = QtWidgets.QPushButton(self.groupBox_validation)
        self.pushButtonFinish.setEnabled(True)
        self.pushButtonFinish.setMinimumSize(QtCore.QSize(0, 41))
        self.pushButtonFinish.setObjectName(_fromUtf8("pushButtonFinish"))
        self.gridLayout_2.addWidget(self.pushButtonFinish, 1, 1, 1, 1)
        font.setPointSize(12)
        self.groupBox_log.raise_()
        self.groupBox_identite.raise_()
        self.logo_ins.raise_()
        self.groupBox_validation.raise_()
        # self.pushButtonResume.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 994, 17))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.groupBox_identite.setTitle(_translate("MainWindow", "IDENTITY", None))
        self.labelName.setText(_translate("MainWindow", "last name", None))
        self.labelFirstname.setText(_translate("MainWindow", "first name", None))
        self.labelBirthdate.setText(_translate("MainWindow", "birth date", None))
        self.labelSexe.setText(_translate("MainWindow", "sex", None))
        self.radioButtonM.setText(_translate("MainWindow", "M", None))
        self.radioButtonF.setText(_translate("MainWindow", "F", None))
        self.anonymize_patient_checkBox.setText(_translate("MainWindow", "anonymize", None))
        '''self.groupBox_implantation.setTitle(_translate("MainWindow", "IMPLANTATION INFORMATION", None))
        self.label_10.setText(_translate("MainWindow", "Electrodes type", None))
        __sortingEnabled = self.listElectrodeTypes.isSortingEnabled()
        self.listElectrodeTypes.setSortingEnabled(False)
        item = self.listElectrodeTypes.item(0)
        item.setText(_translate("MainWindow", "Dixi", None))
        item = self.listElectrodeTypes.item(1)
        item.setText(_translate("MainWindow", "Alcis", None))
        item = self.listElectrodeTypes.item(2)
        item.setText(_translate("MainWindow", "AdTech", None))
        item = self.listElectrodeTypes.item(3)
        item.setText(_translate("MainWindow", "Autres", None))
        self.listElectrodeTypes.setSortingEnabled(__sortingEnabled)
        self.comboBoxImplantation.setItemText(0, _translate("MainWindow", "choose type of file", None))
        self.comboBoxImplantation.setItemText(1, _translate("MainWindow", "Scheme", None))
        self.comboBoxImplantation.setItemText(2, _translate("MainWindow", "Xray", None))
        self.comboBoxImplantation.setItemText(3, _translate("MainWindow", "Screenshots", None))'''
        # self.groupBox_neuroimagerie.setTitle(_translate("MainWindow", "NEUROIMAGERY", None))
        # self.import_neuroimagery.setText(_translate("MainWindow", "import_neuroimagery", None))
        # self.groupBox_seeg.setTitle(_translate("MainWindow", "IEEG", None))
        # self.import_ieeg.setText(_translate("MainWindow", "import_ieeg", None))
        # self.groupBox_meg.setTitle(_translate("MainWindow", "MEG", None))
        # self.import_meg.setText(_translate("MainWindow", "import_meg", None))
        # self.groupBox_eeg.setTitle(_translate("MainWindow", "EEG", None))
        # self.import_eeg.setText(_translate("MainWindow", "import_eeg", None))
        # self.pushButtonResume.setText(_translate("MainWindow", "local resume", None))
        self.groupBox_validation.setTitle(_translate("MainWindow", "VALIDATION", None))
        self.pushButtonValidation.setText(_translate("MainWindow", "Validate and format", None))
        self.pushButtonReset.setText(_translate("MainWindow", "Reset", None))
        self.pushButtonFinish.setText(_translate('MainWindow', 'Finish and Import', None))

